### ISSUE TITLE
Test doesn't work

### ISSUE THREAD

**Issue by jacobwilliams** [agoose77/qt-jsonschema-form#2]
The `test.py` produces this error:

```
Traceback (most recent call last):
  File "/qt-jsonschema-form/test.py", line 65, in <module>
    form = builder.create_form(schema, ui_schema)
  File "/qt-jsonschema-form/qt_jsonschema_form/form.py", line 52, in create_form
    validator_cls.check_schema(schema)
  File "/miniconda3/lib/python3.9/site-packages/jsonschema/validators.py", line 231, in check_schema
    raise exceptions.SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: [{'type': 'string', 'pattern': "[a-zA-Z\\-'\\s]+", 'enum': ['Jack', 'Jill']}, {'type': 'string', 'pattern': "[a-zA-Z\\-'\\s]+", 'enum': ['Alice', 'Bob']}] is not of type 'object', 'boolean'
```

I'm using Python 3.9.15, pyqt 5.15.7, jsonschema 4.17.3.

**Comment by agoose77** [comment]
Hi! Yes, this project needs updating to the latest schema draft. If you modify the schema to specify 2019:

```json
{ 
	"$schema": "https://json-schema.org/draft/2019-09/schema",
 	...
}
```
then it should work!

**Comment by agoose77** [comment]
"Fixed" in main. In reality, we need to update the library to handle multiple schema drafts.
